export const CREATE_COURCE = "CREATE_COURCE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";

// Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_COURENT_USER = "SET_COURENT_USER";
export const SET_AUTH_TRUE = "SET_AUTH_TRUE";
//register
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
// Admin

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const UPDATE_USER = " UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const CREATE_USER = "CREATE_USER";
export const CREATE_NEW_USER_FAIL = "CREATE_NEW_USER_FAIL";
//Category

//Video

export const UPLOAD_VIDEO = "UPLOAD_VIDEO";
export const GET_FORMATION_VIDEOS_REQUEST = "GET_FORMATION_VIDEOS_REQUEST";
export const GET_FORMATION_VIDEOS_SUCCESS = "GET_FORMATION_VIDEOS_SUCCESS";
export const GET_FORMATION_VIDEOS_FAIL = "GET_FORMATION_VIDEOS_FAIL";
//ROLES
export const CREATE_NEW_ROLE = " CREATE_NEW_ROLE";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const DELETE_ROLE = "DELETE_ROLE";
// Formations

export const GET_USER_FORMATIONS_REQUEST = "GET_USER_FORMATIONS_REQUEST";
export const GET_USER_FORMATIONS_SUCCESS = "GET_USER_FORMATIONS_SUCCESS";
export const GET_USER_FORMATIONS_FAIL = "GET_USER_FORMATIONS_FAIL";
export const GET_ADMIN_FORMATIONS_REQUEST = "GET_ADMIN_FORMATIONS_REQUEST";
export const GET_ADMIN_FORMATIONS_SUCCESS = "GET_ADMIN_FORMATIONS_SUCCESS";
export const GET_ADMIN_FORMATIONS_FAIL = "GET_ADMIN_FORMATIONS_FAIL";

export const UPDATE_FORMATION = "UPDATE_FORMATION";
export const DELETE_FORMATION = "DELETE_FORMATION";
export const CREATE_FORMATION = "CREATE_FORMATION";
